

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class CampingsPerFestival : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the CampingsPerFestival entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CampingsPerFestival()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CampingsPerFestival(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CampingsPerFestival> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CampingsPerFestival.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CampingsPerFestival_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CampingsPerFestival_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int fest_id
        {
            get
            {
                return global::LightSwitchApplication.CampingsPerFestival.DetailsClass.GetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.fest_id);
            }
            set
            {
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass.SetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.fest_id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fest_id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fest_id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fest_id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int camp_id
        {
            get
            {
                return global::LightSwitchApplication.CampingsPerFestival.DetailsClass.GetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.camp_id);
            }
            set
            {
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass.SetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.camp_id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void camp_id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void camp_id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void camp_id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Camping Camping
        {
            get
            {
                return global::LightSwitchApplication.CampingsPerFestival.DetailsClass.GetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Camping);
            }
            set
            {
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass.SetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Camping, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Camping_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Camping_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Camping_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Festival Festival
        {
            get
            {
                return global::LightSwitchApplication.CampingsPerFestival.DetailsClass.GetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Festival);
            }
            set
            {
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass.SetValue(this, global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Festival, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Festival_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Festival_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Festival_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CampingsPerFestival,
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass,
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass.IImplementation,
                global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.fest_id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass>.Entry
                __CampingsPerFestivalEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass>.Entry(
                    global::LightSwitchApplication.CampingsPerFestival.DetailsClass.__CampingsPerFestival_CreateNew,
                    global::LightSwitchApplication.CampingsPerFestival.DetailsClass.__CampingsPerFestival_Created,
                    global::LightSwitchApplication.CampingsPerFestival.DetailsClass.__CampingsPerFestival_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CampingsPerFestival __CampingsPerFestival_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CampingsPerFestival> es)
            {
                return new global::LightSwitchApplication.CampingsPerFestival(es);
            }
            private static void __CampingsPerFestival_Created(global::LightSwitchApplication.CampingsPerFestival e)
            {
                e.CampingsPerFestival_Created();
            }
            private static bool __CampingsPerFestival_AllowSaveWithErrors(global::LightSwitchApplication.CampingsPerFestival e)
            {
                bool result = false;
                e.CampingsPerFestival_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int> fest_id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.fest_id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int> camp_id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.camp_id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Camping> Camping
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Camping) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Camping>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Festival> Festival
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Festival) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Festival>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int fest_id { get; set; }
                new int camp_id { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Camping { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Festival { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Entry
                    fest_id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Entry(
                        "fest_id",
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._fest_id_Stub,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._fest_id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._fest_id_Validate,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._fest_id_GetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._fest_id_SetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._fest_id_OnValueChanged);
                private static void _fest_id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Data> c, global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, object sf)
                {
                    c(d, ref d._fest_id, sf);
                }
                private static bool _fest_id_ComputeIsReadOnly(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    bool result = false;
                    e.fest_id_IsReadOnly(ref result);
                    return result;
                }
                private static void _fest_id_Validate(global::LightSwitchApplication.CampingsPerFestival e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.fest_id_Validate(r);
                }
                private static int _fest_id_GetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    return d.ImplementationEntity.fest_id;
                }
                private static void _fest_id_SetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, int v)
                {
                    d.ImplementationEntity.fest_id = v;
                }
                private static void _fest_id_OnValueChanged(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    e.fest_id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Entry
                    camp_id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Entry(
                        "camp_id",
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._camp_id_Stub,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._camp_id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._camp_id_Validate,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._camp_id_GetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._camp_id_SetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._camp_id_OnValueChanged);
                private static void _camp_id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Data> c, global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, object sf)
                {
                    c(d, ref d._camp_id, sf);
                }
                private static bool _camp_id_ComputeIsReadOnly(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    bool result = false;
                    e.camp_id_IsReadOnly(ref result);
                    return result;
                }
                private static void _camp_id_Validate(global::LightSwitchApplication.CampingsPerFestival e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.camp_id_Validate(r);
                }
                private static int _camp_id_GetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    return d.ImplementationEntity.camp_id;
                }
                private static void _camp_id_SetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, int v)
                {
                    d.ImplementationEntity.camp_id = v;
                }
                private static void _camp_id_OnValueChanged(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    e.camp_id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Camping>.Entry
                    Camping = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Camping>.Entry(
                        "Camping",
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_Stub,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_ComputeIsReadOnly,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_Validate,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_GetCoreImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_GetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_SetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_Refresh,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Camping_OnValueChanged);
                private static void _Camping_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Camping>.Data> c, global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, object sf)
                {
                    c(d, ref d._Camping, sf);
                }
                private static bool _Camping_ComputeIsReadOnly(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    bool result = false;
                    e.Camping_IsReadOnly(ref result);
                    return result;
                }
                private static void _Camping_Validate(global::LightSwitchApplication.CampingsPerFestival e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Camping_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Camping_GetCoreImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    return d.ImplementationEntity.Camping;
                }
                private static global::LightSwitchApplication.Camping _Camping_GetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Camping, global::LightSwitchApplication.Camping.DetailsClass>(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Camping, ref d._Camping);
                }
                private static void _Camping_SetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, global::LightSwitchApplication.Camping v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Camping, ref d._Camping, (i, ev) => i.Camping = ev, v);
                }
                private static void _Camping_Refresh(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Camping, ref d._Camping);
                }
                private static void _Camping_OnValueChanged(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    e.Camping_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Festival>.Entry
                    Festival = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Festival>.Entry(
                        "Festival",
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_Stub,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_ComputeIsReadOnly,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_Validate,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_GetCoreImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_GetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_SetImplementationValue,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_Refresh,
                        global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties._Festival_OnValueChanged);
                private static void _Festival_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Festival>.Data> c, global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, object sf)
                {
                    c(d, ref d._Festival, sf);
                }
                private static bool _Festival_ComputeIsReadOnly(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    bool result = false;
                    e.Festival_IsReadOnly(ref result);
                    return result;
                }
                private static void _Festival_Validate(global::LightSwitchApplication.CampingsPerFestival e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Festival_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Festival_GetCoreImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    return d.ImplementationEntity.Festival;
                }
                private static global::LightSwitchApplication.Festival _Festival_GetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Festival, global::LightSwitchApplication.Festival.DetailsClass>(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Festival, ref d._Festival);
                }
                private static void _Festival_SetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d, global::LightSwitchApplication.Festival v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Festival, ref d._Festival, (i, ev) => i.Festival = ev, v);
                }
                private static void _Festival_Refresh(global::LightSwitchApplication.CampingsPerFestival.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CampingsPerFestival.DetailsClass.PropertySetProperties.Festival, ref d._Festival);
                }
                private static void _Festival_OnValueChanged(global::LightSwitchApplication.CampingsPerFestival e)
                {
                    e.Festival_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Data _fest_id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, int>.Data _camp_id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Camping>.Data _Camping;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CampingsPerFestival, global::LightSwitchApplication.CampingsPerFestival.DetailsClass, global::LightSwitchApplication.Festival>.Data _Festival;
            
        }
    
        #endregion
    }
    
    #endregion
}
