

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Faciliteiten : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Faciliteiten entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Faciliteiten()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Faciliteiten(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Faciliteiten> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Faciliteiten.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Faciliteiten_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Faciliteiten_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int fac_id
        {
            get
            {
                return global::LightSwitchApplication.Faciliteiten.DetailsClass.GetValue(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string fac_omschr
        {
            get
            {
                return global::LightSwitchApplication.Faciliteiten.DetailsClass.GetValue(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_omschr);
            }
            set
            {
                global::LightSwitchApplication.Faciliteiten.DetailsClass.SetValue(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_omschr, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_omschr_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_omschr_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_omschr_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal fac_eenhprijs
        {
            get
            {
                return global::LightSwitchApplication.Faciliteiten.DetailsClass.GetValue(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_eenhprijs);
            }
            set
            {
                global::LightSwitchApplication.Faciliteiten.DetailsClass.SetValue(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_eenhprijs, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_eenhprijs_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_eenhprijs_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void fac_eenhprijs_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.FacPerCamp> FacPerCamps
        {
            get
            {
                return global::LightSwitchApplication.Faciliteiten.DetailsClass.GetValue(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.FacPerCamps);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.FacPerCamp> FacPerCampsQuery
        {
            get
            {
                return global::LightSwitchApplication.Faciliteiten.DetailsClass.GetQuery(this, global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.FacPerCamps);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Faciliteiten,
                global::LightSwitchApplication.Faciliteiten.DetailsClass,
                global::LightSwitchApplication.Faciliteiten.DetailsClass.IImplementation,
                global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass>.Entry
                __FaciliteitenEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass>.Entry(
                    global::LightSwitchApplication.Faciliteiten.DetailsClass.__Faciliteiten_CreateNew,
                    global::LightSwitchApplication.Faciliteiten.DetailsClass.__Faciliteiten_Created,
                    global::LightSwitchApplication.Faciliteiten.DetailsClass.__Faciliteiten_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Faciliteiten __Faciliteiten_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Faciliteiten> es)
            {
                return new global::LightSwitchApplication.Faciliteiten(es);
            }
            private static void __Faciliteiten_Created(global::LightSwitchApplication.Faciliteiten e)
            {
                e.Faciliteiten_Created();
            }
            private static bool __Faciliteiten_AllowSaveWithErrors(global::LightSwitchApplication.Faciliteiten e)
            {
                bool result = false;
                e.Faciliteiten_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, int> fac_id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, string> fac_omschr
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_omschr) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, decimal> fac_eenhprijs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.fac_eenhprijs) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, global::LightSwitchApplication.FacPerCamp> FacPerCamps
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.FacPerCamps) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, global::LightSwitchApplication.FacPerCamp>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int fac_id { get; }
                new string fac_omschr { get; set; }
                new decimal fac_eenhprijs { get; set; }
                new global::System.Collections.IEnumerable FacPerCamps { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, int>.Entry
                    fac_id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, int>.Entry(
                        "fac_id",
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_id_Stub,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_id_Validate,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_id_OnValueChanged);
                private static void _fac_id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Faciliteiten.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, int>.Data> c, global::LightSwitchApplication.Faciliteiten.DetailsClass d, object sf)
                {
                    c(d, ref d._fac_id, sf);
                }
                private static bool _fac_id_ComputeIsReadOnly(global::LightSwitchApplication.Faciliteiten e)
                {
                    bool result = false;
                    e.fac_id_IsReadOnly(ref result);
                    return result;
                }
                private static void _fac_id_Validate(global::LightSwitchApplication.Faciliteiten e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.fac_id_Validate(r);
                }
                private static int _fac_id_GetImplementationValue(global::LightSwitchApplication.Faciliteiten.DetailsClass d)
                {
                    return d.ImplementationEntity.fac_id;
                }
                private static void _fac_id_OnValueChanged(global::LightSwitchApplication.Faciliteiten e)
                {
                    e.fac_id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, string>.Entry
                    fac_omschr = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, string>.Entry(
                        "fac_omschr",
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_omschr_Stub,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_omschr_ComputeIsReadOnly,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_omschr_Validate,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_omschr_GetImplementationValue,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_omschr_SetImplementationValue,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_omschr_OnValueChanged);
                private static void _fac_omschr_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Faciliteiten.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, string>.Data> c, global::LightSwitchApplication.Faciliteiten.DetailsClass d, object sf)
                {
                    c(d, ref d._fac_omschr, sf);
                }
                private static bool _fac_omschr_ComputeIsReadOnly(global::LightSwitchApplication.Faciliteiten e)
                {
                    bool result = false;
                    e.fac_omschr_IsReadOnly(ref result);
                    return result;
                }
                private static void _fac_omschr_Validate(global::LightSwitchApplication.Faciliteiten e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.fac_omschr_Validate(r);
                }
                private static string _fac_omschr_GetImplementationValue(global::LightSwitchApplication.Faciliteiten.DetailsClass d)
                {
                    return d.ImplementationEntity.fac_omschr;
                }
                private static void _fac_omschr_SetImplementationValue(global::LightSwitchApplication.Faciliteiten.DetailsClass d, string v)
                {
                    d.ImplementationEntity.fac_omschr = v;
                }
                private static void _fac_omschr_OnValueChanged(global::LightSwitchApplication.Faciliteiten e)
                {
                    e.fac_omschr_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, decimal>.Entry
                    fac_eenhprijs = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, decimal>.Entry(
                        "fac_eenhprijs",
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_eenhprijs_Stub,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_eenhprijs_ComputeIsReadOnly,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_eenhprijs_Validate,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_eenhprijs_GetImplementationValue,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_eenhprijs_SetImplementationValue,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._fac_eenhprijs_OnValueChanged);
                private static void _fac_eenhprijs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Faciliteiten.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Faciliteiten.DetailsClass d, object sf)
                {
                    c(d, ref d._fac_eenhprijs, sf);
                }
                private static bool _fac_eenhprijs_ComputeIsReadOnly(global::LightSwitchApplication.Faciliteiten e)
                {
                    bool result = false;
                    e.fac_eenhprijs_IsReadOnly(ref result);
                    return result;
                }
                private static void _fac_eenhprijs_Validate(global::LightSwitchApplication.Faciliteiten e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.fac_eenhprijs_Validate(r);
                }
                private static decimal _fac_eenhprijs_GetImplementationValue(global::LightSwitchApplication.Faciliteiten.DetailsClass d)
                {
                    return d.ImplementationEntity.fac_eenhprijs;
                }
                private static void _fac_eenhprijs_SetImplementationValue(global::LightSwitchApplication.Faciliteiten.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.fac_eenhprijs = v;
                }
                private static void _fac_eenhprijs_OnValueChanged(global::LightSwitchApplication.Faciliteiten e)
                {
                    e.fac_eenhprijs_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, global::LightSwitchApplication.FacPerCamp>.Entry
                    FacPerCamps = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, global::LightSwitchApplication.FacPerCamp>.Entry(
                        "FacPerCamps",
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._FacPerCamps_Stub,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._FacPerCamps_GetReferencedEntities,
                        global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties._FacPerCamps_GetEntityCollection);
                private static void _FacPerCamps_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Faciliteiten.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, global::LightSwitchApplication.FacPerCamp>.Data> c, global::LightSwitchApplication.Faciliteiten.DetailsClass d, object sf)
                {
                    c(d, ref d._FacPerCamps, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.FacPerCamp> _FacPerCamps_GetReferencedEntities(global::LightSwitchApplication.Faciliteiten.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.FacPerCamp, global::LightSwitchApplication.FacPerCamp.DetailsClass>(global::LightSwitchApplication.Faciliteiten.DetailsClass.PropertySetProperties.FacPerCamps, ref d._FacPerCamps);
                }
                private static global::System.Collections.IEnumerable _FacPerCamps_GetEntityCollection(global::LightSwitchApplication.Faciliteiten.DetailsClass d)
                {
                    return d.ImplementationEntity.FacPerCamps;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, int>.Data _fac_id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, string>.Data _fac_omschr;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, decimal>.Data _fac_eenhprijs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Faciliteiten, global::LightSwitchApplication.Faciliteiten.DetailsClass, global::LightSwitchApplication.FacPerCamp>.Data _FacPerCamps;
            
        }
    
        #endregion
    }
    
    #endregion
}
