

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Tickettype : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Tickettype entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Tickettype()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Tickettype(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Tickettype> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Tickettype.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tickettype_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tickettype_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int typ_id
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string typ_omschr
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_omschr);
            }
            set
            {
                global::LightSwitchApplication.Tickettype.DetailsClass.SetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_omschr, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_omschr_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_omschr_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_omschr_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal typ_prijs
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_prijs);
            }
            set
            {
                global::LightSwitchApplication.Tickettype.DetailsClass.SetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_prijs, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_prijs_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_prijs_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void typ_prijs_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Ticket> Tickets
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.Tickets);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Ticket> TicketsQuery
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetQuery(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.Tickets);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TickettypesPerFestival> TickettypesPerFestivals
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetValue(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.TickettypesPerFestivals);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TickettypesPerFestival> TickettypesPerFestivalsQuery
        {
            get
            {
                return global::LightSwitchApplication.Tickettype.DetailsClass.GetQuery(this, global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.TickettypesPerFestivals);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Tickettype,
                global::LightSwitchApplication.Tickettype.DetailsClass,
                global::LightSwitchApplication.Tickettype.DetailsClass.IImplementation,
                global::LightSwitchApplication.Tickettype.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass>.Entry
                __TickettypeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass>.Entry(
                    global::LightSwitchApplication.Tickettype.DetailsClass.__Tickettype_CreateNew,
                    global::LightSwitchApplication.Tickettype.DetailsClass.__Tickettype_Created,
                    global::LightSwitchApplication.Tickettype.DetailsClass.__Tickettype_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Tickettype __Tickettype_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Tickettype> es)
            {
                return new global::LightSwitchApplication.Tickettype(es);
            }
            private static void __Tickettype_Created(global::LightSwitchApplication.Tickettype e)
            {
                e.Tickettype_Created();
            }
            private static bool __Tickettype_AllowSaveWithErrors(global::LightSwitchApplication.Tickettype e)
            {
                bool result = false;
                e.Tickettype_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Tickettype.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, int> typ_id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, string> typ_omschr
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_omschr) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, decimal> typ_prijs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.typ_prijs) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.Ticket> Tickets
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.Tickets) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.Ticket>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.TickettypesPerFestival> TickettypesPerFestivals
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.TickettypesPerFestivals) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.TickettypesPerFestival>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int typ_id { get; }
                new string typ_omschr { get; set; }
                new decimal typ_prijs { get; set; }
                new global::System.Collections.IEnumerable Tickets { get; }
                new global::System.Collections.IEnumerable TickettypesPerFestivals { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, int>.Entry
                    typ_id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, int>.Entry(
                        "typ_id",
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_id_Stub,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_id_Validate,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_id_OnValueChanged);
                private static void _typ_id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Tickettype.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, int>.Data> c, global::LightSwitchApplication.Tickettype.DetailsClass d, object sf)
                {
                    c(d, ref d._typ_id, sf);
                }
                private static bool _typ_id_ComputeIsReadOnly(global::LightSwitchApplication.Tickettype e)
                {
                    bool result = false;
                    e.typ_id_IsReadOnly(ref result);
                    return result;
                }
                private static void _typ_id_Validate(global::LightSwitchApplication.Tickettype e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.typ_id_Validate(r);
                }
                private static int _typ_id_GetImplementationValue(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.ImplementationEntity.typ_id;
                }
                private static void _typ_id_OnValueChanged(global::LightSwitchApplication.Tickettype e)
                {
                    e.typ_id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, string>.Entry
                    typ_omschr = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, string>.Entry(
                        "typ_omschr",
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_omschr_Stub,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_omschr_ComputeIsReadOnly,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_omschr_Validate,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_omschr_GetImplementationValue,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_omschr_SetImplementationValue,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_omschr_OnValueChanged);
                private static void _typ_omschr_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Tickettype.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, string>.Data> c, global::LightSwitchApplication.Tickettype.DetailsClass d, object sf)
                {
                    c(d, ref d._typ_omschr, sf);
                }
                private static bool _typ_omschr_ComputeIsReadOnly(global::LightSwitchApplication.Tickettype e)
                {
                    bool result = false;
                    e.typ_omschr_IsReadOnly(ref result);
                    return result;
                }
                private static void _typ_omschr_Validate(global::LightSwitchApplication.Tickettype e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.typ_omschr_Validate(r);
                }
                private static string _typ_omschr_GetImplementationValue(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.ImplementationEntity.typ_omschr;
                }
                private static void _typ_omschr_SetImplementationValue(global::LightSwitchApplication.Tickettype.DetailsClass d, string v)
                {
                    d.ImplementationEntity.typ_omschr = v;
                }
                private static void _typ_omschr_OnValueChanged(global::LightSwitchApplication.Tickettype e)
                {
                    e.typ_omschr_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, decimal>.Entry
                    typ_prijs = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, decimal>.Entry(
                        "typ_prijs",
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_prijs_Stub,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_prijs_ComputeIsReadOnly,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_prijs_Validate,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_prijs_GetImplementationValue,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_prijs_SetImplementationValue,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._typ_prijs_OnValueChanged);
                private static void _typ_prijs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Tickettype.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Tickettype.DetailsClass d, object sf)
                {
                    c(d, ref d._typ_prijs, sf);
                }
                private static bool _typ_prijs_ComputeIsReadOnly(global::LightSwitchApplication.Tickettype e)
                {
                    bool result = false;
                    e.typ_prijs_IsReadOnly(ref result);
                    return result;
                }
                private static void _typ_prijs_Validate(global::LightSwitchApplication.Tickettype e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.typ_prijs_Validate(r);
                }
                private static decimal _typ_prijs_GetImplementationValue(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.ImplementationEntity.typ_prijs;
                }
                private static void _typ_prijs_SetImplementationValue(global::LightSwitchApplication.Tickettype.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.typ_prijs = v;
                }
                private static void _typ_prijs_OnValueChanged(global::LightSwitchApplication.Tickettype e)
                {
                    e.typ_prijs_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.Ticket>.Entry
                    Tickets = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.Ticket>.Entry(
                        "Tickets",
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._Tickets_Stub,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._Tickets_GetReferencedEntities,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._Tickets_GetEntityCollection);
                private static void _Tickets_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Tickettype.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.Ticket>.Data> c, global::LightSwitchApplication.Tickettype.DetailsClass d, object sf)
                {
                    c(d, ref d._Tickets, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Ticket> _Tickets_GetReferencedEntities(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Ticket, global::LightSwitchApplication.Ticket.DetailsClass>(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.Tickets, ref d._Tickets);
                }
                private static global::System.Collections.IEnumerable _Tickets_GetEntityCollection(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.ImplementationEntity.Tickets;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.TickettypesPerFestival>.Entry
                    TickettypesPerFestivals = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.TickettypesPerFestival>.Entry(
                        "TickettypesPerFestivals",
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._TickettypesPerFestivals_Stub,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._TickettypesPerFestivals_GetReferencedEntities,
                        global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties._TickettypesPerFestivals_GetEntityCollection);
                private static void _TickettypesPerFestivals_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Tickettype.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.TickettypesPerFestival>.Data> c, global::LightSwitchApplication.Tickettype.DetailsClass d, object sf)
                {
                    c(d, ref d._TickettypesPerFestivals, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TickettypesPerFestival> _TickettypesPerFestivals_GetReferencedEntities(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TickettypesPerFestival, global::LightSwitchApplication.TickettypesPerFestival.DetailsClass>(global::LightSwitchApplication.Tickettype.DetailsClass.PropertySetProperties.TickettypesPerFestivals, ref d._TickettypesPerFestivals);
                }
                private static global::System.Collections.IEnumerable _TickettypesPerFestivals_GetEntityCollection(global::LightSwitchApplication.Tickettype.DetailsClass d)
                {
                    return d.ImplementationEntity.TickettypesPerFestivals;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, int>.Data _typ_id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, string>.Data _typ_omschr;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, decimal>.Data _typ_prijs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.Ticket>.Data _Tickets;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Tickettype, global::LightSwitchApplication.Tickettype.DetailsClass, global::LightSwitchApplication.TickettypesPerFestival>.Data _TickettypesPerFestivals;
            
        }
    
        #endregion
    }
    
    #endregion
}
